title = "jpshackelford"
# logo = "URL to logo"
base_url = "http://localhost:3000"
about = "John-Mason Shackelford is a software product leader and DevOps expert."
index_site_pages = ["main","blog"]

[extra]
copyright = "2023 John-Mason Shackelford"
github = "https://github.com/jpshackelford"
# twitter = "https://twitter.com/fermyontech"

date_style = "%B %e, %Y"
